version: "3.7"
services:
  app:
    build:
      args:
        user: insure-bro
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: insure-bro
    container_name: insure-bro-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - insure-bro-network

  nginx:
    image: nginx:alpine
    container_name: insure-bro-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - insure-bro-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insure-bro
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - insure-bro-network
    ports:
      - 3306:3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - cluster.name=supercluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - "discovery.zen.ping.unicast.hosts=10.11.12.13:9300,10.11.12.13:9301,10.11.12.13:9302"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - insure-bro-network


networks:
  insure-bro-network:
    driver: bridge

volumes:
  db-data:
  es-data:






