version: "3.7"
services:
  app:
    build:
      args:
        user: insure-bro
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: insure-bro
    container_name: insure-bro-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - insure-bro-network

  nginx:
    image: nginx:alpine
    container_name: insure-bro-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - insure-bro-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insure-bro
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - insure-bro-network
    ports:
      - 3306:3306

networks:
  insure-bro-network:
    driver: bridge

volumes:
  db-data:
